baseURL = 'https://JonasViana.github.io/blog_games/'
languageCode = 'pt-br'
title = 'Blog Games'
theme = 'PaperMod'

[params]
    showFullContents = false
    displayFullPostContent = false

[params.homeInfoParams]
    Title = "Bem-vindo ao Blog Games! 🎮"
    Content = "Notícias, Reviews e tudo sobre o mundo dos vídeo games."

[[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10