baseURL = 'https://JonasViana.github.io/blog_games/'
languageCode = 'pt-br'
title = 'Foco Games'
theme = 'PaperMod'

[params]
    showFullContents = false
    displayFullPostContent = false
    mainSections = ["posts"]

[params.homeInfoParams]
    Title = "Bem-vindo ao Foco Games! 🎮"
    Content = "Notícias, Reviews e tudo sobre o mundo dos vídeo games."

[[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

    [[menu.main]]
    name = "Notícias"
    url = "categories/noticias/"
    weight = 10

[[menu.main]]
    name = "Reviews"
    url = "categories/reviews/"
    weight = 20

[[menu.main]]
    name = "Guias"
    url = "categories/guias/"
    weight = 30

[[menu.main]]
    name = "Promoções"
    url = "categories/promocoes/"
    weight = 40

[[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 100

[[menu.main]]
    name = "Contato"
    url = "/contato/"
    weight = 110

[[menu.main]]
    name = "Privacidade"
    url = "/privacidade/"
    weight = 120